name: Periodic Develop Build

permissions:
  contents: write

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - name: Checkout qmk_firmware
      uses: actions/checkout@v4
      with:
        ref: develop
        repository: 'qmk/qmk_firmware'

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y rsync doxygen
        # install nvm
        touch $HOME/.bashrc
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

    - name: Install node
      run: |
        source $HOME/.bashrc
        nvm install 20
        nvm use 20
        corepack enable

    - name: Patch docs
      run: |
        echo "develop-docs.qmk.fm" > docs/public/CNAME
        sed -i 's^QMK Firmware^QMK Firmare - Develop^g' builddefs/docsgen/.vitepress/config.mts
        sed -i 's^edit/master/docs^edit/develop/docs^g' builddefs/docsgen/.vitepress/config.mts
        sed -i 's^"https://github.com/qmk/qmk_firmware"^"https://github.com/qmk/qmk_firmware/tree/develop"^g' builddefs/docsgen/.vitepress/config.mts

    - name: Build docs
      run: |
        source $HOME/.bashrc
        nvm use 20
        qmk --verbose generate-docs

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .build/docs
          clean: true
          single-commit: true
          git-config-name: QMK Bot
          git-config-email: hello@qmk.fm
